### ISSUE TITLE
Block Card Doesn't Work If A Player Has Already Won

### ISSUE THREAD

**Issue by alrafiabdullah** [MTG2000/uno#1]
##
So, I was playing with the bot. When the right hand side bot won, the block button didn't work any more. If I opponent play that card on me, I could still draw or play cards. Most probably due to that player was still counted as a player even after the win. I may not be able to describe the situation properly, let me know if you need further information. Thank you.
##

**Comment by MTG2000** [comment]
Yeah, you are right.
I wasn't considering this case.
should be fixed now 👍
